[package]
name = "rustpython-arabiya"
description = "Arabic keyword translation for the شِفرة (Shifra) programming language"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
rustpython-vm = { workspace = true, optional = true }

[lints]
workspace = true

[features]
vm = ["dep:rustpython-vm"]
